defaults: &defaults
  docker:
    - image: gcr.io/planet-4-151612/p4-builder:v0.9.1
  working_directory:  /home/circleci/

version: 2

jobs:
  build-develop:
    <<: *defaults
    environment:
      APP_HOSTNAME: k8s.p4.greenpeace.org
      APP_HOSTPATH: base
      CLOUDSQL_INSTANCE: p4-develop-k8s
      CONTAINER_PREFIX: planet4-base
      GOOGLE_PROJECT_ID: planet-4-151612
      HELM_NAMESPACE: develop
      WP_DB_NAME: planet4-base_wordpress
      WP_TITLE: Greenpeace Base Development
    steps:
      - setup_remote_docker

      - run:
          name: Configure
          command: |
            ${HOME}/scripts/activate-gcloud-account.sh
            mkdir -p /tmp/workspace/var
            echo "${CIRCLE_BUILD_NUM}" > /tmp/workspace/var/circle-build-num

      - run:
          name: Build
          working_directory: /home/circleci
          command: |
            if make
            then
              TYPE="Build" ${HOME}/scripts/notify-job-success.sh
            else
              TYPE="Build" ${HOME}/scripts/notify-job-failure.sh
              exit 1
            fi

      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - var

  # test:
  #   <<: *defaults
  #   steps:
  #     - run:
  #         name: Placeholder
  #         command: |
  #           echo "Branch: ${CIRCLE_BRANCH}"
  #           echo "Build:  ${CIRCLE_BUILD_NUM}"
  #           echo "Tag:    ${CIRCLE_TAG}"
  #           echo "No tests implemented yet"

  deploy-develop:
    <<: *defaults
    environment:
      APP_HOSTNAME: k8s.p4.greenpeace.org
      APP_HOSTPATH: base
      CLOUDSQL_INSTANCE: p4-develop-k8s
      CONTAINER_PREFIX: planet4-base
      GOOGLE_PROJECT_ID: planet-4-151612
      HELM_NAMESPACE: develop
      WP_DB_NAME: planet4-base_wordpress
      WP_TITLE: Greenpeace Base Development
    steps:
      - attach_workspace:
          at: /tmp/workspace

      - run:
          name: Configure
          command: |
            ${HOME}/scripts/activate-gcloud-account.sh

      - run:
          name: Deploy new containers
          environment:
            NEWRELIC_APPNAME: P4 base Development
          command: |
            BUILD_TAG="build-$(cat /tmp/workspace/var/circle-build-num)" \
            make deploy

workflows:
  version: 2
  develop:
    jobs:
    - build-develop:
        context: org-global
        filters:
          branches:
            only: develop
          tags:
            ignore: /^v.*/

    - deploy-develop:
        context: org-global
        requires:
          - build-develop
        filters:
          branches:
            only: develop
